name: build-ios-app
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Fastlane
        run: fastlane distributeApplicationLocally
        working-directory: Source/fastlane
        env:  # Make sure 'env' aligns with 'run' and 'working-directory'
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}
