name: build-ios-app
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Fastlane
        run: fastlane beta
        working-directory: Source/fastlane
        env:  # Make sure 'env' aligns with 'run' and 'working-directory'
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
