name: build-ios-app
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Fastlane
        run: fastlane distributeApplicationLocally
        working-directory: Source/fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
